version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    ports:
      - 8000:8000
    depends_on:
      - "mongo"
    command: "uvicorn app.main:app  --host 0.0.0.0  --reload --port
      8000  --log-level debug"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: filoenna
      MONGO_INITDB_ROOT_PASSWORD: secretkey
